#' polished: streamlined downloader and cleaner for WHO POLIS data
#'
#' Provides [get_polis_data()] for incremental, parallel-friendly downloads
#' from the POLIS OData API, a set of standalone cleaners
#' ([clean_afp()], [clean_es()], [clean_sia()], [clean_virus()]) wired
#' together by [run_pipeline()], and EPID-driven recovery of missing
#' administrative geography via [impute_geo_from_epid()].
#'
#' @section NAMESPACE imports:
#' `dplyr`'s set-operation generics (`setdiff`, `intersect`, `union`) are
#' imported into the package namespace so unqualified calls inside the
#' package dispatch on data.frames instead of falling back to base R's
#' vector-only versions -- which would crash the change-log diff with
#' "argument is of length zero". `.data` is imported to support tidy-eval
#' NSE inside internal helpers.
#'
#' @keywords internal
#' @importFrom dplyr setdiff intersect union .data
#' @importFrom utils capture.output globalVariables
"_PACKAGE"

# Silence the R CMD check NOTE that lists every bare column name used in
# dplyr/tidyverse NSE expressions across the cleaning pipeline. These are
# POLIS column names (mixed CamelCase, snake.case, and dotted) plus a
# handful of helper variables created inside dplyr chains.
utils::globalVariables(c(
  # shape-lookup count column
  ".n",
  # coordinate-recovery join helpers
  ".crow",
  ".yr",
  ".year_ok",
  # auto_parse_types() / detect_factors() NSE column names
  "is_char",
  "lead0",
  "n_unique",
  "n_non_na",
  "unique_ratio",
  "keep",
  "reason",
  "protected",
  # cleaner-derived columns (bare names in NSE expressions)
  "collection_date",
  "date_from",
  "virus_date",
  "paralysis_onset_date",
  "year_onset",
  "month_onset",
  "age_months",
  "onset_to_stool1",
  "onset_to_stool2",
  "stool1_to_stool2",
  "onset_to_followup",
  "onset_date_quality",
  "timeliness",
  "needs_60day_followup",
  # POLIS API column names (CamelCase + space-separated)
  "ADM0_GUID",
  "ADM0_NAME",
  "ADM0_NAME.rep",
  "ADM1_GUID",
  "ADM1_NAME",
  "ADM2_NAME",
  "API_Name",
  "Admin 0 Id",
  "Admin 1 Id",
  "Admin 2 Guid",
  "Admin 2 Id",
  "Admin0Guid",
  "Admin0OfficialName",
  "Admin1Name",
  "Admin1OfficialName",
  "Admin2Name",
  "Admin2OfficialName",
  "DateFrom",
  "Doses",
  "DosesOPVNumber",
  "ENDDATE",
  "EPID",
  "Env Sample Manual Edit Id",
  "GUID",
  "ISO_3_CODE",
  "Id",
  "SIA Sub-Activity Code",
  "SIASubActivityCode",
  "STARTDATE",
  "Sample Id",
  "Shape",
  "Site Code",
  "Site Name",
  "Table",
  "Virus ID",
  "Virus Sequenced",
  "X",

  # internal snake/dot-case column names
  "active.year.01",
  "activity.start.date",
  "adm0guid",
  "adm1guid",
  "adm2guid",
  "admin.0",
  "admin.0.guid",
  "admin.1.guid",
  "admin.2.guid",
  "admin.coverage.%",
  "admin0guid",
  "admin1guid",
  "admin2guid",
  "age.group",
  "calculated.age.(months)",
  "case.date",
  "case.miss.guid",
  "categorical_response_set.x",
  "categorical_response_set.y",
  "cdc.last.camp",
  "cdc.max.round",
  "cdc.round.num",
  "character.n_unique",
  "classification",
  "classificationvdpv",
  "clinical.admitted.date",
  "cluster",
  "cluster_method",
  "collect.date",
  "collect.yr",
  "collection.date",
  "combine.distinct.01",
  "congo_wild1",
  "count",
  "country.iso3",
  "created.date",
  "createddate",
  "ctry",
  "ctry.guid",
  "datasource",
  "date.notification.to.hq",
  "date.onset",
  "date_time",
  "dateinvest",
  "datenotificationtohq",
  "datenotify",
  "datestool1",
  "datestool2",
  "diff.distinct.01",
  "dist.guid",
  "doses.total",
  "emergence.group",
  "emergence_group",
  "emergencegroup",
  "env.sample.id",
  "env.sample.manual.edit.id",
  "epid",
  "epid.in.polis",
  "epid_fixed",
  "es.dups",
  "final.cell.culture.result",
  "followup.date",
  "geo.corrected",
  "hot.case",
  "id",
  "im.loaded",
  "in_new_not_old",
  "in_old_not_new",
  "investigation.date",
  "ipv.campaigns",
  "last.updated.date",
  "lat",
  "latitude",
  "lng",
  "location",
  "lon",
  "longitude",
  "lqas.loaded",
  "match01",
  "measurement",
  "missing.guid",
  "n",
  "name",
  "new",
  "new_categorical_response_set",
  "no_match",
  "notification.date",
  "nperarm",
  "nt.changes",
  "ntchanges",
  "old",
  "old.distinct.01",
  "old_categorical_response_set",
  "ontonot",
  "ontonot.14",
  "ontonot.60",
  "ontostool2",
  "ontostool2.03",
  "paralysis.asymmetric",
  "paralysis.onset.fever",
  "paralysis.rapid.progress",
  "planned.campaigns",
  "poliovirustypes",
  "polis.case.id",
  "polis.latitude",
  "polis.longitude",
  "pons.epid",
  "prov.guid",
  "publishdate",
  "response",
  "same",
  "sample.condition",
  "sample.id",
  "short_name",
  "sia.code",
  "sia.sub.activity.code",
  "site.code",
  "site.id",
  "site.name",
  "skim_type",
  "skim_variable",
  "status",
  "stool.1.collection.date",
  "stool.1.condition",
  "stool.2.collection.date",
  "stool.2.condition",
  "stool.date.sent.to.ic.lab",
  "stool.date.sent.to.lab",
  "stool1missing",
  "stool1tostool2",
  "stool2missing",
  "sub.activity.initial.planned.date",
  "sub.activity.last.updated.date",
  "sub.activity.start.date",
  "surveillance.type",
  "surveillancetypename",
  "time.to.response",
  "timeliness.01",
  "vaccine.source",
  "vaccine.type",
  "vaccine_source",
  "value",
  "var_class.x",
  "var_class.y",
  "var_name",
  "variable",
  "vdpvclassificationchangedate",
  "vdpvclassificationcode",
  "virus.cluster",
  "virus.date",
  "virus.id",
  "virus.type",
  "virus.type(s)",
  "virus.type.01",
  "virus_dup",
  "virustype",
  "virustypename",
  "vtype",
  "vtype.fixed",
  "who.region",
  "whoregion",
  "wrongAdmin0GUID",
  "wrongAdmin1GUID",
  "wrongAdmin2GUID",
  "x",
  "y",
  "year",
  "yr.end",
  "yr.sia",
  "yr.st",

  # canonical cleaned schema (modular cleaners)
  "date_collection",
  "date_onset",
  "date_start",
  "sub_activity_id",

  # EPID geo cascade (epid_geo.R) helpers
  ":=",
  "k_prefix",
  "m_prefix"
))
